id: P008108
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:02:07.538350
source_metadata:
  id: bdr:W1KG18530
  title: ཤ་ཟ་མི་རིགས་པའི་ཚུལ་དཀར་ཆོས་ནང་པའི་མཛེས་རྒྱན།
  author: ''
  volumes:
    d588f28b4222494d853ec96d3dbc7895:
      image_group_id: I1KG18547
      title: Volume 1 of sha za mi rigs pa'i tshul dkar chos nang pa'i mdzes rgyan/
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
