id: P008108
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18530
  title: ཤ་ཟ་མི་རིགས་པའི་ཚུལ་དཀར་ཆོས་ནང་པའི་མཛེས་རྒྱན།
  author: ''
  volumes:
    2452c4886c1d4bbfb0540c57b9940833:
      image_group_id: I1KG18547
      title: ''
      volume_number: 1
      total_pages: 112
ebook_metadata:
  title: ཤ་ཟ་མི་རིགས་པའི་ཚུལ་དཀར་ཆོས་ནང་པའི་མཛེས་རྒྱན།
  author: ''
  sku: P008108
  cover: cover.jpg
  layers:
  - pagination
