id: I5B8CD5AD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T21:59:32+00:00'
last_modified: '2022-06-09T04:33:35.466367+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18530
  title: ཤ་ཟ་མི་རིགས་པའི་ཚུལ་དཀར་ཆོས་ནང་པའི་མཛེས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CD7E:
      image_group_id: I1KG18547
      title: Volume 1 of sha za mi rigs pa'i tshul dkar chos nang pa'i mdzes rgyan/
      total_pages: 112
      order: 1
      base_file: CD7E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
